spring.application.name=loldatos

spring.datasource.url=jdbc:mysql://localhost:3306/loldatos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml


