spring.application.name=loldatos

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
server.port=${PORT:8080}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml


